//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import type { ModelResult as $ModelResult } from "@zenstackhq/orm";
export type User = $ModelResult<$Schema, "User">;
export type Post = $ModelResult<$Schema, "Post">;
export type Comment = $ModelResult<$Schema, "Comment">;
export type Org = $ModelResult<$Schema, "Org">;
export type Team = $ModelResult<$Schema, "Team">;
export type TeamMember = $ModelResult<$Schema, "TeamMember">;
export type Project = $ModelResult<$Schema, "Project">;
export type Task = $ModelResult<$Schema, "Task">;
export type WorkLog = $ModelResult<$Schema, "WorkLog">;
export type Label = $ModelResult<$Schema, "Label">;
export type TaskLabel = $ModelResult<$Schema, "TaskLabel">;
export type Document = $ModelResult<$Schema, "Document">;
