import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import type { ExtractManifest, ExtractedQuery } from "./types.js";

/** Expression for the client that performs the call (inside generated `run`). */
function emitInnerClientRef(dbAlias: string): string {
  // `this.db` / `this.prisma` in app code — harness passes the same client as `db`.
  if (dbAlias.startsWith("this.")) {
    return "db";
  }
  if (dbAlias === "prisma") return "db";
  return dbAlias;
}

function needsTransactionWrapper(
  dbAlias: string,
  transactionAliases: Set<string>
): boolean {
  if (dbAlias.startsWith("this.")) return false;
  if (dbAlias === "db" || dbAlias === "prisma") return false;
  return transactionAliases.has(dbAlias);
}

function buildRunnerBody(q: ExtractedQuery, transactionAliases: Set<string>): string {
  const inner = emitInnerClientRef(q.dbAlias);
  const args = q.argsSource.trim();
  const hasArgs = args.length > 0;

  const call = hasArgs
    ? `${inner}.${q.model}.${q.method}(${args})`
    : `${inner}.${q.model}.${q.method}()`;

  if (needsTransactionWrapper(q.dbAlias, transactionAliases)) {
    const param = q.dbAlias;
    // PrismaClient.$transaction is not on ZenstackCompareDb's index signature; cast for generated harness.
    return `return (db as unknown as { $transaction: (fn: (${param}: ZenstackCompareDb) => Promise<unknown>) => Promise<unknown> }).$transaction(async (${param}) => ${call});`;
  }
  return `return ${call};`;
}

function emitParamType(q: ExtractedQuery): string {
  if (q.params.length === 0) return "Record<string, never>";
  const lines = q.params.map((p) => `  ${JSON.stringify(p.name)}: ${p.typeText || "unknown"};`);
  return `{\n${lines.join("\n")}\n}`;
}

function emitParamDestructure(q: ExtractedQuery): string {
  if (q.params.length === 0) return "";
  return `const { ${q.params.map((p) => p.name).join(", ")} } = params;`;
}

function generateQueryFile(
  q: ExtractedQuery,
  opts: { headerComment?: string; transactionAliases?: string[] } = {}
): string {
  const txAliases = new Set(opts.transactionAliases ?? ["tx"]);
  const header =
    opts.headerComment ??
    "// Auto-generated by zenstack-query-compare — do not edit by hand.";
  const meta = {
    id: q.id,
    file: q.file,
    line: q.line,
    column: q.column,
    dbAlias: q.dbAlias,
    model: q.model,
    method: q.method,
  };
  const body = buildRunnerBody(q, txAliases);

  return `${header}

import { type QueryMeta, type ZenstackCompareDb } from "./_shared.js";

export const queryMeta: QueryMeta = ${JSON.stringify(meta, null, 2)};

export type QueryParams = ${emitParamType(q)};

export default async function runQuery(
  db: ZenstackCompareDb,
  params: QueryParams
): Promise<unknown> {
  ${emitParamDestructure(q)}
  ${body}
}
`;
}

export function writeManifestJson(
  outDir: string,
  manifest: ExtractManifest
): void {
  fs.mkdirSync(outDir, { recursive: true });
  const p = path.join(outDir, "extract-manifest.json");
  fs.writeFileSync(p, JSON.stringify(manifest, null, 2), "utf8");
}

function sharedModuleSource(): string {
  return `// Auto-generated by zenstack-query-compare — shared helpers.

/** Minimal db shape: ZenStack-enhanced client (same surface as Prisma delegate API). */
export type ZenstackCompareDb = Record<string, Record<string, (...args: unknown[]) => Promise<unknown>>>;

export type QueryMeta = {
  id: string;
  file: string;
  line: number;
  column: number;
  dbAlias: string;
  model: string;
  method: string;
};
`;
}

function comparePackageJsonSource(): string {
  return JSON.stringify(
    {
      name: "zenstack-compare-harness",
      private: true,
      type: "module",
      scripts: {
        "generate:v2":
          "npm exec --yes --package=zenstack@2.22.2 -- zenstack generate --schema ./zenstack/schema.v2.zmodel -o ./zenstack/v2",
        "generate:v3":
          "zen generate --schema ./zenstack/schema.v3.zmodel -o ./zenstack/v3 --silent",
        "build:zenstack-schema": "tsc -p ./tsconfig.zenstack.json",
        "generate:clients":
          "npm run generate:v2 && npm run generate:v3 && npm run build:zenstack-schema",
        compare:
          "zenstack-query-compare compare --cwd . --queries-dir ./queries --enhance-v2 ./enhance-v2.mjs --enhance-v3 ./enhance-v3.mjs --json",
        "compare:results":
          "zenstack-query-compare compare --cwd . --queries-dir ./queries --enhance-v2 ./enhance-v2.mjs --enhance-v3 ./enhance-v3.mjs --ignore-sql-diff --json",
        "compare:md":
          "npm run generate:clients && zenstack-query-compare compare --cwd . --queries-dir ./queries --enhance-v2 ./enhance-v2.mjs --enhance-v3 ./enhance-v3.mjs --ignore-sql-diff --md-out ./sql-report.md",
      },
      dependencies: {
        "@prisma/client": "^6.5.0",
        "@zenstackhq/orm": "^3.5.1",
        "@zenstackhq/runtime-v2": "npm:@zenstackhq/runtime@^2.22.1",
        "better-sqlite3": "^12.8.0",
        pg: "^8.20.0",
      },
      devDependencies: {
        "@zenstackhq/cli": "^3.5.1",
        "@zenstackhq/schema": "^3.5.1",
        prisma: "^6.5.0",
        typescript: "^5.7.3",
      },
    },
    null,
    2
  );
}

function enhanceV2EntrypointSource(): string {
  return `import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { createRequire } from "node:module";
import { createEnhancement } from "@zenstackhq/runtime-v2/enhancements/node";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);
const prismaModule = require("@prisma/client");

function tryLoadJson(p) {
  try {
    return JSON.parse(readFileSync(p, "utf8"));
  } catch {
    return undefined;
  }
}

export function enhance(prisma) {
  const modelMeta = tryLoadJson(path.join(__dirname, "zenstack-generated", "model-meta.json"));
  const policy = tryLoadJson(path.join(__dirname, "zenstack-generated", "policy.json"));
  return createEnhancement(prisma, {
    modelMeta,
    policy,
    prismaModule,
  });
}
`;
}

function enhanceV3EntrypointSource(): string {
  return `import path from "node:path";
import { fileURLToPath } from "node:url";
import Database from "better-sqlite3";
import pg from "pg";
import { ZenStackClient } from "@zenstackhq/orm";
import { SqliteDialect } from "@zenstackhq/orm/dialects/sqlite";
import { PostgresDialect } from "@zenstackhq/orm/dialects/postgres";
import { schema } from "./zenstack/v3/schema.js";

const { Pool } = pg;
const __dirname = path.dirname(fileURLToPath(import.meta.url));

function isPostgresUrl(url) {
  return typeof url === "string" && (url.startsWith("postgresql:") || url.startsWith("postgres:"));
}

export function enhance(_prisma, _ctx, options = {}) {
  const sqlCapture = Array.isArray(options.sqlCapture) ? options.sqlCapture : undefined;
  const log =
    sqlCapture ?
      (event) => {
        if (event.level === "query" && event.query?.sql) sqlCapture.push(String(event.query.sql).trim());
      }
    : undefined;

  const dbUrl = process.env.DATABASE_URL;
  if (isPostgresUrl(dbUrl)) {
    return new ZenStackClient(schema, {
      dialect: new PostgresDialect({ pool: new Pool({ connectionString: dbUrl }) }),
      log: log ?? undefined,
    });
  }

  const sqlitePath =
    typeof dbUrl === "string" && dbUrl.startsWith("file:")
      ? path.resolve(__dirname, dbUrl.slice("file:".length))
      : path.join(__dirname, "prisma", "dev.db");

  return new ZenStackClient(schema, {
    dialect: new SqliteDialect({ database: new Database(sqlitePath) }),
    log: log ?? undefined,
  });
}
`;
}

function writeCompareHarnessScaffold(outDir: string, manifest: ExtractManifest): void {
  fs.mkdirSync(outDir, { recursive: true });
  fs.writeFileSync(path.join(outDir, "package.json"), comparePackageJsonSource() + "\n", "utf8");
  fs.writeFileSync(path.join(outDir, "enhance-v2.mjs"), enhanceV2EntrypointSource(), "utf8");
  fs.writeFileSync(path.join(outDir, "enhance-v3.mjs"), enhanceV3EntrypointSource(), "utf8");
  fs.writeFileSync(
    path.join(outDir, "tsconfig.zenstack.json"),
    JSON.stringify(
      {
        compilerOptions: {
          target: "ES2022",
          module: "NodeNext",
          moduleResolution: "NodeNext",
          skipLibCheck: true,
        },
        include: ["zenstack/v3/**/*.ts"],
      },
      null,
      2
    ) + "\n",
    "utf8"
  );

  const zmodelContents = manifest.zmodelContents ?? {};
  const schemaZmodelEntry =
    Object.entries(zmodelContents).find(([rel]) => rel === "schema.zmodel") ??
    Object.entries(zmodelContents).find(([rel]) => rel.endsWith("/schema.zmodel")) ??
    Object.entries(zmodelContents)[0];
  if (schemaZmodelEntry) {
    const [, schemaTextV3] = schemaZmodelEntry;
    const zenstackDir = path.join(outDir, "zenstack");
    fs.mkdirSync(zenstackDir, { recursive: true });
    fs.writeFileSync(path.join(zenstackDir, "schema.v3.zmodel"), schemaTextV3, "utf8");
    fs.writeFileSync(
      path.join(zenstackDir, "schema.v2.zmodel"),
      deriveV2ZmodelFromV3(schemaTextV3),
      "utf8"
    );
  }

  const prismaSchemaSrc = findPrismaSchema(manifest.root);
  const prismaSchemaDst = path.join(outDir, "prisma", "schema.prisma");
  if (prismaSchemaSrc && fs.existsSync(prismaSchemaSrc)) {
    fs.mkdirSync(path.dirname(prismaSchemaDst), { recursive: true });
    fs.copyFileSync(prismaSchemaSrc, prismaSchemaDst);
  }

  const modelMetaSrc = path.join(manifest.root, "zenstack-generated", "model-meta.json");
  const policySrc = path.join(manifest.root, "zenstack-generated", "policy.json");
  const generatedDstDir = path.join(outDir, "zenstack-generated");
  if (fs.existsSync(modelMetaSrc)) {
    fs.mkdirSync(generatedDstDir, { recursive: true });
    fs.copyFileSync(modelMetaSrc, path.join(generatedDstDir, "model-meta.json"));
  }
  if (fs.existsSync(policySrc)) {
    fs.mkdirSync(generatedDstDir, { recursive: true });
    fs.copyFileSync(policySrc, path.join(generatedDstDir, "policy.json"));
  }
}

function deriveV2ZmodelFromV3(v3Schema: string): string {
  let out = v3Schema;
  // Conservative compatibility rewrite bucket for known v3-first syntax forms.
  out = out.replace(/@@\s*auth\s*\(/g, "@@allow(");
  out = inlineModelMixins(out);
  out = removeTypeDeclarations(out);
  out = stripComputedAttributes(out);
  out = stripWithBlocks(out);
  return out;
}

function inlineModelMixins(schema: string): string {
  const typeBodies = collectTypeBodies(schema);
  if (typeBodies.size === 0) return schema;

  return schema.replace(
    /^([ \t]*model\s+[A-Za-z_][A-Za-z0-9_]*)(\s+)with\s+([^\{\n]+)\{/gm,
    (full, modelHead: string, _gap: string, withPart: string) => {
      const mixinNames = withPart
        .split(",")
        .map((x) => x.trim())
        .filter(Boolean);
      if (mixinNames.length === 0) return `${modelHead} {`;

      const modelIndent = (modelHead.match(/^[ \t]*/) ?? [""])[0]!;
      const fieldIndent = `${modelIndent}  `;
      const inlinedBodies = mixinNames
        .map((name) => typeBodies.get(name))
        .filter((x): x is string => Boolean(x))
        .map((body) => indentBlock(body, fieldIndent));

      if (inlinedBodies.length === 0) return `${modelHead} {`;
      return `${modelHead} {\n${inlinedBodies.join("\n")}\n`;
    }
  );
}

function collectTypeBodies(schema: string): Map<string, string> {
  const out = new Map<string, string>();
  const typeDecl = /^[ \t]*type\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{/gm;
  let m: RegExpExecArray | null;

  while ((m = typeDecl.exec(schema)) !== null) {
    const typeName = m[1]!;
    const openBrace = schema.indexOf("{", m.index);
    if (openBrace < 0) continue;

    let i = openBrace + 1;
    let depth = 1;
    while (i < schema.length && depth > 0) {
      const ch = schema[i]!;
      if (ch === "{") depth += 1;
      else if (ch === "}") depth -= 1;
      i += 1;
    }
    if (depth !== 0) continue;

    const body = schema.slice(openBrace + 1, i - 1).trim();
    out.set(typeName, body);
  }

  return out;
}

function indentBlock(block: string, indent: string): string {
  const lines = block.replace(/\r\n/g, "\n").split("\n");
  let minIndent = Number.POSITIVE_INFINITY;
  for (const line of lines) {
    if (!line.trim()) continue;
    const m = line.match(/^[ \t]*/);
    minIndent = Math.min(minIndent, (m?.[0] ?? "").length);
  }
  if (!Number.isFinite(minIndent)) minIndent = 0;

  return lines
    .map((line) => {
      if (!line.trim()) return "";
      return `${indent}${line.slice(minIndent)}`;
    })
    .join("\n");
}

function removeTypeDeclarations(schema: string): string {
  return schema.replace(
    /^[ \t]*type\s+[A-Za-z_][A-Za-z0-9_]*\s*\{[\s\S]*?^[ \t]*\}/gm,
    ""
  );
}

function stripComputedAttributes(schema: string): string {
  return schema.replace(/\s+@computed\b/g, "");
}

function stripWithBlocks(input: string): string {
  let i = 0;
  let out = "";
  let inLineComment = false;
  let inBlockComment = false;
  let inSingle = false;
  let inDouble = false;

  const isIdent = (ch: string | undefined): boolean =>
    !!ch && /[A-Za-z0-9_]/.test(ch);

  while (i < input.length) {
    const c = input[i]!;
    const n = input[i + 1];

    if (inLineComment) {
      out += c;
      if (c === "\n") inLineComment = false;
      i += 1;
      continue;
    }
    if (inBlockComment) {
      out += c;
      if (c === "*" && n === "/") {
        out += "/";
        i += 2;
        inBlockComment = false;
      } else {
        i += 1;
      }
      continue;
    }
    if (inSingle) {
      out += c;
      if (c === "\\") {
        if (n) {
          out += n;
          i += 2;
        } else {
          i += 1;
        }
        continue;
      }
      if (c === "'") inSingle = false;
      i += 1;
      continue;
    }
    if (inDouble) {
      out += c;
      if (c === "\\") {
        if (n) {
          out += n;
          i += 2;
        } else {
          i += 1;
        }
        continue;
      }
      if (c === '"') inDouble = false;
      i += 1;
      continue;
    }

    if (c === "/" && n === "/") {
      out += "//";
      i += 2;
      inLineComment = true;
      continue;
    }
    if (c === "/" && n === "*") {
      out += "/*";
      i += 2;
      inBlockComment = true;
      continue;
    }
    if (c === "'") {
      out += c;
      i += 1;
      inSingle = true;
      continue;
    }
    if (c === '"') {
      out += c;
      i += 1;
      inDouble = true;
      continue;
    }

    if (
      input.slice(i, i + 4) === "with" &&
      !isIdent(input[i - 1]) &&
      !isIdent(input[i + 4])
    ) {
      let j = i + 4;
      while (j < input.length && /\s/.test(input[j]!)) j += 1;
      if (input[j] === "{") {
        j += 1;
        let depth = 1;
        while (j < input.length && depth > 0) {
          const ch = input[j]!;
          if (ch === "{") depth += 1;
          else if (ch === "}") depth -= 1;
          j += 1;
        }
        i = j;
        continue;
      }
    }

    out += c;
    i += 1;
  }

  return out;
}

function findPrismaSchema(root: string): string | null {
  const preferred = path.join(root, "prisma", "schema.prisma");
  if (fs.existsSync(preferred)) return preferred;

  const matches = fg.sync(["**/schema.prisma"], {
    cwd: root,
    absolute: true,
    onlyFiles: true,
    ignore: [
      "**/node_modules/**",
      "**/.git/**",
      "**/dist/**",
      "**/.zenstack-compare/**",
    ],
  });
  if (matches.length === 0) return null;

  const prismaNamed = matches.find((m) => /(^|\/)prisma\/schema\.prisma$/.test(m));
  if (prismaNamed) return prismaNamed;
  return matches.sort((a, b) => a.length - b.length)[0] ?? null;
}

export function writeQueriesDir(
  outDir: string,
  manifest: ExtractManifest,
  opts?: { transactionAliases?: string[] }
): string {
  fs.mkdirSync(outDir, { recursive: true });
  const queriesDir = path.join(outDir, "queries");
  fs.rmSync(queriesDir, { recursive: true, force: true });
  fs.mkdirSync(queriesDir, { recursive: true });
  const sharedPath = path.join(queriesDir, "_shared.ts");
  fs.writeFileSync(sharedPath, sharedModuleSource(), "utf8");
  for (const q of manifest.queries) {
    const queryPath = path.join(queriesDir, `${q.id}.ts`);
    fs.writeFileSync(
      queryPath,
      generateQueryFile(q, {
        transactionAliases: opts?.transactionAliases,
      }),
      "utf8"
    );
  }
  const indexPath = path.join(queriesDir, "index.json");
  fs.writeFileSync(
    indexPath,
    JSON.stringify(
      {
        queryIds: manifest.queries.map((q) => q.id),
      },
      null,
      2
    ),
    "utf8"
  );
  writeManifestJson(outDir, manifest);
  writeCompareHarnessScaffold(outDir, manifest);
  return queriesDir;
}
