import fs from "node:fs";
import path from "node:path";
import type { ExtractManifest, ExtractedQuery } from "./types.js";

function zmodelBundleLiteral(manifest: ExtractManifest): string {
  const contents = manifest.zmodelContents ?? {};
  return JSON.stringify(contents, null, 2);
}

/** Expression for the client that performs the call (inside generated `run`). */
function emitInnerClientRef(dbAlias: string): string {
  if (dbAlias.startsWith("this.")) {
    const prop = dbAlias.slice("this.".length);
    if (!/^[a-zA-Z_$][\w$]*$/.test(prop)) {
      return "db";
    }
    return `(db as unknown as { ${prop}: typeof db }).${prop}`;
  }
  if (dbAlias === "prisma") return "db";
  return dbAlias;
}

function needsTransactionWrapper(
  dbAlias: string,
  transactionAliases: Set<string>
): boolean {
  if (dbAlias.startsWith("this.")) return false;
  if (dbAlias === "db" || dbAlias === "prisma") return false;
  return transactionAliases.has(dbAlias);
}

function buildRunnerBody(
  q: ExtractedQuery,
  transactionAliases: Set<string>
): string {
  const inner = emitInnerClientRef(q.dbAlias);
  const args = q.argsSource.trim();
  const call =
    args.length === 0 ?
      `${inner}.${q.model}.${q.method}()`
    : `${inner}.${q.model}.${q.method}(${args})`;

  if (needsTransactionWrapper(q.dbAlias, transactionAliases)) {
    const param = q.dbAlias;
    // PrismaClient.$transaction is not on ZenstackCompareDb's index signature; cast for generated harness.
    return `return (db as unknown as { $transaction: (fn: (${param}: ZenstackCompareDb) => Promise<unknown>) => Promise<unknown> }).$transaction(async (${param}) => ${call});`;
  }
  return `return ${call};`;
}

export function generateQueriesModule(
  manifest: ExtractManifest,
  opts: { headerComment?: string; transactionAliases?: string[] } = {}
): string {
  const txAliases = new Set(opts.transactionAliases ?? ["tx"]);
  const header =
    opts.headerComment ??
    `// Auto-generated by zenstack-query-compare — do not edit by hand.\n// Source root: ${manifest.root}\n// Generated at: ${manifest.extractedAt}`;

  const entries = manifest.queries.map((q) => {
    const body = buildRunnerBody(q, txAliases);
    const meta = {
      id: q.id,
      file: q.file,
      line: q.line,
      column: q.column,
      dbAlias: q.dbAlias,
      model: q.model,
      method: q.method,
    };
    return `  ${JSON.stringify(q.id)}: {\n    meta: ${JSON.stringify(meta, null, 2).replace(/\n/g, "\n    ")},\n    run: async (db) => {\n      ${body}\n    },\n  }`;
  });

  return `${header}

/** Minimal db shape: ZenStack-enhanced client (same surface as Prisma delegate API). */
export type ZenstackCompareDb = Record<string, Record<string, (...args: unknown[]) => Promise<unknown>>>;

export type QueryMeta = {
  id: string;
  file: string;
  line: number;
  column: number;
  dbAlias: string;
  model: string;
  method: string;
};

export type QueryBundle = {
  meta: QueryMeta;
  run: (db: ZenstackCompareDb) => Promise<unknown>;
};

export const zenstackCompareQueries: Record<string, QueryBundle> = {
${entries.join(",\n\n")},
};

export const zenstackCompareQueryList: QueryBundle[] = Object.values(zenstackCompareQueries);

export const zenstackCompareManifest = ${JSON.stringify(
    {
      version: manifest.version,
      root: manifest.root,
      extractedAt: manifest.extractedAt,
      zmodelFiles: manifest.zmodelFiles,
      queryCount: manifest.queries.length,
    },
    null,
    2
  )} as const;

/** Relative zmodel path -> file text as captured at extract time (see extract-manifest.json). */
export const zenstackCompareZmodelContents = ${zmodelBundleLiteral(manifest)} as Record<string, string>;

export function getZmodelCombinedSource(): string {
  return zenstackCompareManifest.zmodelFiles
    .map((f) => \`// ----- \${f} -----\\n\${zenstackCompareZmodelContents[f] ?? ""}\`)
    .join("\\n\\n");
}
`;
}

/** Write companion JSON manifest with full detail including raw args (for audit). */
export function writeManifestJson(
  outDir: string,
  manifest: ExtractManifest
): void {
  fs.mkdirSync(outDir, { recursive: true });
  const p = path.join(outDir, "extract-manifest.json");
  fs.writeFileSync(p, JSON.stringify(manifest, null, 2), "utf8");
}

export function writeQueriesTs(
  outDir: string,
  manifest: ExtractManifest,
  opts?: { transactionAliases?: string[] }
): string {
  fs.mkdirSync(outDir, { recursive: true });
  const tsPath = path.join(outDir, "queries.ts");
  fs.writeFileSync(
    tsPath,
    generateQueriesModule(manifest, {
      transactionAliases: opts?.transactionAliases,
    }),
    "utf8"
  );
  writeManifestJson(outDir, manifest);
  return tsPath;
}
