import fs from "node:fs";
import path from "node:path";
import type { ExtractManifest, ExtractedQuery } from "./types.js";

function zmodelBundleLiteral(manifest: ExtractManifest): string {
  const contents = manifest.zmodelContents ?? {};
  return JSON.stringify(contents, null, 2);
}

function buildRunnerBody(q: ExtractedQuery): string {
  const args = q.argsSource.trim();
  if (args.length === 0) {
    return `return db.${q.model}.${q.method}();`;
  }
  return `return db.${q.model}.${q.method}(${args});`;
}

export function generateQueriesModule(
  manifest: ExtractManifest,
  opts: { headerComment?: string } = {}
): string {
  const header =
    opts.headerComment ??
    `// Auto-generated by zenstack-query-compare — do not edit by hand.\n// Source root: ${manifest.root}\n// Generated at: ${manifest.extractedAt}`;

  const entries = manifest.queries.map((q) => {
    const body = buildRunnerBody(q);
    const meta = {
      id: q.id,
      file: q.file,
      line: q.line,
      column: q.column,
      dbAlias: q.dbAlias,
      model: q.model,
      method: q.method,
    };
    return `  ${JSON.stringify(q.id)}: {\n    meta: ${JSON.stringify(meta, null, 2).replace(/\n/g, "\n    ")},\n    run: async (db) => {\n      ${body}\n    },\n  }`;
  });

  return `${header}

/** Minimal db shape: ZenStack-enhanced client (same surface as Prisma delegate API). */
export type ZenstackCompareDb = Record<string, Record<string, (...args: unknown[]) => Promise<unknown>>>;

export type QueryMeta = {
  id: string;
  file: string;
  line: number;
  column: number;
  dbAlias: string;
  model: string;
  method: string;
};

export type QueryBundle = {
  meta: QueryMeta;
  run: (db: ZenstackCompareDb) => Promise<unknown>;
};

export const zenstackCompareQueries: Record<string, QueryBundle> = {
${entries.join(",\n\n")},
};

export const zenstackCompareQueryList: QueryBundle[] = Object.values(zenstackCompareQueries);

export const zenstackCompareManifest = ${JSON.stringify(
    {
      version: manifest.version,
      root: manifest.root,
      extractedAt: manifest.extractedAt,
      zmodelFiles: manifest.zmodelFiles,
      queryCount: manifest.queries.length,
    },
    null,
    2
  )} as const;

/** Relative zmodel path -> file text as captured at extract time (see extract-manifest.json). */
export const zenstackCompareZmodelContents = ${zmodelBundleLiteral(manifest)} as Record<string, string>;

export function getZmodelCombinedSource(): string {
  return zenstackCompareManifest.zmodelFiles
    .map((f) => \`// ----- \${f} -----\\n\${zenstackCompareZmodelContents[f] ?? ""}\`)
    .join("\\n\\n");
}
`;
}

/** Write companion JSON manifest with full detail including raw args (for audit). */
export function writeManifestJson(
  outDir: string,
  manifest: ExtractManifest
): void {
  fs.mkdirSync(outDir, { recursive: true });
  const p = path.join(outDir, "extract-manifest.json");
  fs.writeFileSync(p, JSON.stringify(manifest, null, 2), "utf8");
}

export function writeQueriesTs(
  outDir: string,
  manifest: ExtractManifest
): string {
  fs.mkdirSync(outDir, { recursive: true });
  const tsPath = path.join(outDir, "queries.ts");
  fs.writeFileSync(tsPath, generateQueriesModule(manifest), "utf8");
  writeManifestJson(outDir, manifest);
  return tsPath;
}
