/**
 * Emit a standalone seed script for a Prisma project using @faker-js/faker.
 * The script is run in the target app (must have @faker-js/faker installed).
 */
import { createRequire } from "node:module";
import path from "node:path";

type DmmfField = {
  name: string;
  kind: string;
  type: string;
  isList: boolean;
  isRequired: boolean;
  isId?: boolean;
  hasDefaultValue?: boolean;
  isReadOnly?: boolean;
  relationName?: string | null;
  relationFromFields?: string[];
};

type DmmfModel = { name: string; fields: DmmfField[] };

function delegateKey(modelName: string): string {
  return modelName.charAt(0).toLowerCase() + modelName.slice(1);
}

/** Models in safe create order (dependencies first). */
export function prismaModelCreationOrder(models: DmmfModel[]): DmmfModel[] {
  const byName = new Map(models.map((m) => [m.name, m]));
  const indegree = new Map<string, number>();
  const children = new Map<string, string[]>();
  for (const m of models) {
    indegree.set(m.name, 0);
    children.set(m.name, []);
  }
  for (const m of models) {
    for (const f of m.fields) {
      if (f.kind === "object" && f.relationFromFields?.length) {
        const parent = f.type;
        if (byName.has(parent)) {
          children.get(parent)!.push(m.name);
          indegree.set(m.name, (indegree.get(m.name) ?? 0) + 1);
        }
      }
    }
  }
  const q: string[] = [];
  for (const [name, d] of indegree) {
    if (d === 0) q.push(name);
  }
  const out: DmmfModel[] = [];
  while (q.length) {
    const n = q.shift()!;
    const mod = byName.get(n);
    if (mod) out.push(mod);
    for (const c of children.get(n) ?? []) {
      const v = (indegree.get(c) ?? 0) - 1;
      indegree.set(c, v);
      if (v === 0) q.push(c);
    }
  }
  if (out.length !== models.length) {
    return models;
  }
  return out;
}

function fkScalarToRefModel(model: DmmfModel): Map<string, string> {
  const m = new Map<string, string>();
  for (const f of model.fields) {
    if (f.kind === "object" && f.relationFromFields?.length) {
      for (const fk of f.relationFromFields) {
        m.set(fk, f.type);
      }
    }
  }
  return m;
}

function fkScalarNames(model: DmmfModel): Set<string> {
  const s = new Set<string>();
  for (const f of model.fields) {
    if (f.kind === "object" && f.relationFromFields?.length) {
      for (const fk of f.relationFromFields) s.add(fk);
    }
  }
  return s;
}

function scalarLine(field: DmmfField): string | null {
  if (field.kind === "enum") {
    return `        ${field.name}: faker.helpers.arrayElement(Object.values(Prisma.${field.type})),`;
  }
  switch (field.type) {
    case "String":
      if (/email/i.test(field.name))
        return `        ${field.name}: \`user_\${faker.string.uuid()}@faker.test\`,`;
      if (/slug/i.test(field.name))
        return `        ${field.name}: faker.string.alphanumeric(8),`;
      if (field.name === "id" || field.name.endsWith("Id"))
        return `        ${field.name}: faker.string.alphanumeric(14),`;
      return `        ${field.name}: faker.lorem.words(2),`;
    case "Int":
      return `        ${field.name}: faker.number.int({ min: 0, max: 9999 }),`;
    case "Float":
      return `        ${field.name}: faker.number.float({ min: 0, max: 100, fractionDigits: 2 }),`;
    case "Decimal":
      return `        ${field.name}: faker.number.float({ min: 0, max: 100, fractionDigits: 2 }),`;
    case "Boolean":
      return `        ${field.name}: faker.datatype.boolean(),`;
    case "DateTime":
      return `        ${field.name}: faker.date.recent(),`;
    case "BigInt":
      return `        ${field.name}: BigInt(faker.number.int({ min: 1, max: 999999 })),`;
    case "Bytes":
      return `        ${field.name}: Buffer.from(faker.string.alphanumeric(8)),`;
    case "Json":
      return `        ${field.name}: {},`;
    default:
      return null;
  }
}

export function generateFakerSeedScriptFromDmmf(opts: {
  models: DmmfModel[];
  recordsPerModel: number;
  fakerSeed: number;
}): string {
  const order = prismaModelCreationOrder(opts.models);
  const lines: string[] = [];
  lines.push(`/** Generated by zenstack-query-compare seed-faker */`);
  lines.push(`import { PrismaClient, Prisma } from "@prisma/client";`);
  lines.push(`import { faker } from "@faker-js/faker";`);
  lines.push(``);
  lines.push(`faker.seed(${opts.fakerSeed});`);
  lines.push(`const prisma = new PrismaClient();`);
  lines.push(`const N = ${opts.recordsPerModel};`);
  lines.push(``);
  lines.push(`async function main() {`);

  for (let i = order.length - 1; i >= 0; i--) {
    const m = order[i]!;
    lines.push(`  await prisma.${delegateKey(m.name)}.deleteMany();`);
  }

  const rowArrays = new Map<string, string>();
  for (const m of order) {
    const key = delegateKey(m.name);
    const arr = `${key}Rows`;
    rowArrays.set(m.name, arr);
    const fkMap = fkScalarToRefModel(m);
    const fkScalars = fkScalarNames(m);

    lines.push(`  const ${arr}: { id: string }[] = [];`);
    lines.push(`  for (let i = 0; i < N; i++) {`);
    lines.push(`    const created = await prisma.${key}.create({`);
    lines.push(`      data: {`);

    for (const f of m.fields) {
      if (f.kind === "object") continue;
      if (f.isReadOnly && !fkScalars.has(f.name)) continue;
      const refModel = fkMap.get(f.name);
      if (refModel) {
        const refArr = rowArrays.get(refModel);
        if (refArr) {
          if (!f.isRequired) {
            lines.push(
              `        ${f.name}: faker.helpers.arrayElement([...${refArr}.map((r) => r.id), null]),`
            );
          } else {
            lines.push(
              `        ${f.name}: faker.helpers.arrayElement(${refArr}.map((r) => r.id)),`
            );
          }
        }
        continue;
      }
      if (f.hasDefaultValue) continue;
      if (!f.isRequired) continue;
      const sl = scalarLine(f);
      if (sl) lines.push(sl);
    }

    lines.push(`      },`);
    lines.push(`    });`);
    const idField =
      m.fields.find((f) => f.isId)?.name ??
      m.fields.find((f) => f.kind === "scalar" && f.name === "id")?.name ??
      "id";
    lines.push(
      `    ${arr}.push({ id: String((created as Record<string, unknown>)["${idField}"]) });`
    );
    lines.push(`  }`);
  }

  lines.push(
    `  console.log("Seeded (faker):", ${JSON.stringify(order.map((m) => m.name))});`
  );
  lines.push(`}`);
  lines.push(``);
  lines.push(
    `main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());`
  );
  return lines.join("\n");
}

export function loadDmmfModels(cwd: string): DmmfModel[] {
  const req = createRequire(path.join(path.resolve(cwd), "package.json"));
  const { Prisma } = req("@prisma/client") as {
    Prisma: { dmmf: { datamodel: { models: DmmfModel[] } } };
  };
  return Prisma.dmmf.datamodel.models;
}
